apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.operator.name }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.agent.name }}
  namespace: {{ .Release.Namespace }}
