// PodReconciler 监听带有 etmem enable 标签的 Pod，自动创建/删除 EtmemPolicy。
// 用户无需手动创建 EtmemPolicy，只需在 Pod 上设置标签和可选的 profile annotation。
// 每个 namespace 最多一个自动策略（etmem-auto），通过 labelSelector 匹配所有 enable=true 的 Pod。
// Profile 解析：如果多个 Pod 指定不同 profile，使用最激进的那个。
package controller

import (
	"context"

	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/types"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/event"
	"sigs.k8s.io/controller-runtime/pkg/log"
	"sigs.k8s.io/controller-runtime/pkg/predicate"

	etmemv1 "github.com/openeuler/etmem-operator/api/v1alpha1"
)

// profilePriority defines aggressiveness order — higher = more aggressive.
var profilePriority = map[string]int{
	"conservative": 1,
	"moderate":     2,
	"aggressive":   3,
	"extreme":      4,
}

type PodReconciler struct {
	client.Client
	Scheme *runtime.Scheme
}

func (r *PodReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	logger := log.FromContext(ctx)

	// List all enable=true Pods in the namespace
	var podList corev1.PodList
	if err := r.List(ctx, &podList,
		client.InNamespace(req.Namespace),
		client.MatchingLabels{etmemv1.LabelEnable: "true"},
	); err != nil {
		return ctrl.Result{}, err
	}

	// Count active Pods and resolve the most aggressive profile
	enabledCount := 0
	resolvedProfile := ""
	for i := range podList.Items {
		pod := &podList.Items[i]
		if pod.Status.Phase == corev1.PodSucceeded || pod.Status.Phase == corev1.PodFailed {
			continue
		}
		enabledCount++
		podProfile := pod.Annotations[etmemv1.AnnotationProfile]
		if podProfile == "" {
			podProfile = etmemv1.DefaultAutoProfile
		}
		if profilePriority[podProfile] > profilePriority[resolvedProfile] {
			resolvedProfile = podProfile
		}
	}

	if enabledCount > 0 {
		if resolvedProfile == "" {
			resolvedProfile = etmemv1.DefaultAutoProfile
		}
		if err := r.ensureAutoPolicy(ctx, req.Namespace, resolvedProfile); err != nil {
			logger.Error(err, "failed to ensure auto-policy", "namespace", req.Namespace)
			return ctrl.Result{}, err
		}
		logger.Info("Auto-policy ensured", "namespace", req.Namespace, "enabledPods", enabledCount, "profile", resolvedProfile)
	} else {
		if err := r.deleteAutoPolicyIfExists(ctx, req.Namespace); err != nil {
			logger.Error(err, "failed to cleanup auto-policy", "namespace", req.Namespace)
			return ctrl.Result{}, err
		}
		logger.V(1).Info("No enabled Pods, auto-policy cleaned up", "namespace", req.Namespace)
	}

	return ctrl.Result{}, nil
}

func (r *PodReconciler) ensureAutoPolicy(ctx context.Context, namespace, profile string) error {
	var existing etmemv1.EtmemPolicy
	err := r.Get(ctx, types.NamespacedName{Name: etmemv1.AutoPolicyName, Namespace: namespace}, &existing)
	if err == nil {
		if existing.Labels[etmemv1.LabelAutoGenerated] != "true" {
			return nil // Not auto-generated; do not overwrite a manually-created policy
		}
		if existing.Spec.Engine.Profile != profile {
			existing.Spec.Engine.Profile = profile
			return r.Update(ctx, &existing)
		}
		return nil
	}
	if !errors.IsNotFound(err) {
		return err
	}

	policy := &etmemv1.EtmemPolicy{
		ObjectMeta: metav1.ObjectMeta{
			Name:      etmemv1.AutoPolicyName,
			Namespace: namespace,
			Labels: map[string]string{
				etmemv1.LabelAutoGenerated: "true",
			},
		},
		Spec: etmemv1.EtmemPolicySpec{
			Selector: &metav1.LabelSelector{
				MatchLabels: map[string]string{
					etmemv1.LabelEnable: "true",
				},
			},
			Engine: etmemv1.EngineSpec{
				Type:    "slide",
				Profile: profile,
			},
		},
	}
	return r.Create(ctx, policy)
}

func (r *PodReconciler) deleteAutoPolicyIfExists(ctx context.Context, namespace string) error {
	var existing etmemv1.EtmemPolicy
	err := r.Get(ctx, types.NamespacedName{Name: etmemv1.AutoPolicyName, Namespace: namespace}, &existing)
	if errors.IsNotFound(err) {
		return nil
	}
	if err != nil {
		return err
	}
	if existing.Labels[etmemv1.LabelAutoGenerated] != "true" {
		return nil
	}
	return r.Delete(ctx, &existing)
}

func (r *PodReconciler) SetupWithManager(mgr ctrl.Manager) error {
	return ctrl.NewControllerManagedBy(mgr).
		For(&corev1.Pod{}).
		WithEventFilter(etmemLabelPredicate{}).
		Complete(r)
}

// etmemLabelPredicate filters Pod events to only those with etmem enable label changes.
type etmemLabelPredicate struct{}

func (p etmemLabelPredicate) Create(e event.CreateEvent) bool {
	return e.Object.GetLabels()[etmemv1.LabelEnable] == "true"
}

func (p etmemLabelPredicate) Update(e event.UpdateEvent) bool {
	oldEnable := e.ObjectOld.GetLabels()[etmemv1.LabelEnable]
	newEnable := e.ObjectNew.GetLabels()[etmemv1.LabelEnable]
	if oldEnable != newEnable {
		return true
	}
	oldProfile := e.ObjectOld.GetAnnotations()[etmemv1.AnnotationProfile]
	newProfile := e.ObjectNew.GetAnnotations()[etmemv1.AnnotationProfile]
	return oldProfile != newProfile
}

func (p etmemLabelPredicate) Delete(e event.DeleteEvent) bool {
	return e.Object.GetLabels()[etmemv1.LabelEnable] == "true"
}

func (p etmemLabelPredicate) Generic(e event.GenericEvent) bool {
	return e.Object.GetLabels()[etmemv1.LabelEnable] == "true"
}

var _ predicate.Predicate = etmemLabelPredicate{}
