package controller

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/types"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client/fake"

	etmemv1 "github.com/openeuler/etmem-operator/api/v1alpha1"
)

func podScheme() *runtime.Scheme {
	s := newScheme()
	_ = corev1.AddToScheme(s)
	return s
}

func TestPodReconciler_CreatesAutoPolicy(t *testing.T) {
	s := podScheme()
	pod := &corev1.Pod{
		ObjectMeta: metav1.ObjectMeta{
			Name: "test-pod", Namespace: "default",
			Labels: map[string]string{etmemv1.LabelEnable: "true"},
		},
		Spec:   corev1.PodSpec{NodeName: "node1"},
		Status: corev1.PodStatus{Phase: corev1.PodRunning},
	}
	c := fake.NewClientBuilder().WithScheme(s).WithObjects(pod).WithStatusSubresource(&etmemv1.EtmemPolicy{}).Build()
	r := &PodReconciler{Client: c, Scheme: s}

	_, err := r.Reconcile(context.Background(), ctrl.Request{
		NamespacedName: types.NamespacedName{Name: "test-pod", Namespace: "default"},
	})
	require.NoError(t, err)

	var policy etmemv1.EtmemPolicy
	err = c.Get(context.Background(), types.NamespacedName{
		Name: etmemv1.AutoPolicyName, Namespace: "default",
	}, &policy)
	require.NoError(t, err)
	assert.Equal(t, "true", policy.Labels[etmemv1.LabelAutoGenerated])
	assert.Equal(t, etmemv1.DefaultAutoProfile, policy.Spec.Engine.Profile)
	assert.Nil(t, policy.Spec.ProcessFilter)
	assert.Equal(t, "true", policy.Spec.Selector.MatchLabels[etmemv1.LabelEnable])
}

func TestPodReconciler_UsesProfileAnnotation(t *testing.T) {
	s := podScheme()
	pod := &corev1.Pod{
		ObjectMeta: metav1.ObjectMeta{
			Name: "test-pod", Namespace: "default",
			Labels:      map[string]string{etmemv1.LabelEnable: "true"},
			Annotations: map[string]string{etmemv1.AnnotationProfile: "extreme"},
		},
		Spec:   corev1.PodSpec{NodeName: "node1"},
		Status: corev1.PodStatus{Phase: corev1.PodRunning},
	}
	c := fake.NewClientBuilder().WithScheme(s).WithObjects(pod).WithStatusSubresource(&etmemv1.EtmemPolicy{}).Build()
	r := &PodReconciler{Client: c, Scheme: s}

	_, err := r.Reconcile(context.Background(), ctrl.Request{
		NamespacedName: types.NamespacedName{Name: "test-pod", Namespace: "default"},
	})
	require.NoError(t, err)

	var policy etmemv1.EtmemPolicy
	err = c.Get(context.Background(), types.NamespacedName{
		Name: etmemv1.AutoPolicyName, Namespace: "default",
	}, &policy)
	require.NoError(t, err)
	assert.Equal(t, "extreme", policy.Spec.Engine.Profile)
}

func TestPodReconciler_MostAggressiveProfileWins(t *testing.T) {
	s := podScheme()
	pod1 := &corev1.Pod{
		ObjectMeta: metav1.ObjectMeta{
			Name: "pod1", Namespace: "default",
			Labels:      map[string]string{etmemv1.LabelEnable: "true"},
			Annotations: map[string]string{etmemv1.AnnotationProfile: "moderate"},
		},
		Spec:   corev1.PodSpec{NodeName: "node1"},
		Status: corev1.PodStatus{Phase: corev1.PodRunning},
	}
	pod2 := &corev1.Pod{
		ObjectMeta: metav1.ObjectMeta{
			Name: "pod2", Namespace: "default",
			Labels:      map[string]string{etmemv1.LabelEnable: "true"},
			Annotations: map[string]string{etmemv1.AnnotationProfile: "extreme"},
		},
		Spec:   corev1.PodSpec{NodeName: "node1"},
		Status: corev1.PodStatus{Phase: corev1.PodRunning},
	}
	c := fake.NewClientBuilder().WithScheme(s).WithObjects(pod1, pod2).WithStatusSubresource(&etmemv1.EtmemPolicy{}).Build()
	r := &PodReconciler{Client: c, Scheme: s}

	_, err := r.Reconcile(context.Background(), ctrl.Request{
		NamespacedName: types.NamespacedName{Name: "pod1", Namespace: "default"},
	})
	require.NoError(t, err)

	var policy etmemv1.EtmemPolicy
	err = c.Get(context.Background(), types.NamespacedName{
		Name: etmemv1.AutoPolicyName, Namespace: "default",
	}, &policy)
	require.NoError(t, err)
	assert.Equal(t, "extreme", policy.Spec.Engine.Profile)
}

func TestPodReconciler_DeletesAutoPolicyWhenNoEnabledPods(t *testing.T) {
	s := podScheme()
	autoPolicy := &etmemv1.EtmemPolicy{
		ObjectMeta: metav1.ObjectMeta{
			Name: etmemv1.AutoPolicyName, Namespace: "default",
			Labels: map[string]string{etmemv1.LabelAutoGenerated: "true"},
		},
		Spec: etmemv1.EtmemPolicySpec{
			Engine: etmemv1.EngineSpec{Type: "slide", Profile: "aggressive"},
		},
	}
	c := fake.NewClientBuilder().WithScheme(s).WithObjects(autoPolicy).Build()
	r := &PodReconciler{Client: c, Scheme: s}

	_, err := r.Reconcile(context.Background(), ctrl.Request{
		NamespacedName: types.NamespacedName{Name: "deleted-pod", Namespace: "default"},
	})
	require.NoError(t, err)

	var policy etmemv1.EtmemPolicy
	err = c.Get(context.Background(), types.NamespacedName{
		Name: etmemv1.AutoPolicyName, Namespace: "default",
	}, &policy)
	assert.True(t, errors.IsNotFound(err))
}

func TestPodReconciler_SkipsNonAutoPolicy(t *testing.T) {
	s := podScheme()
	manualPolicy := &etmemv1.EtmemPolicy{
		ObjectMeta: metav1.ObjectMeta{
			Name: etmemv1.AutoPolicyName, Namespace: "default",
		},
		Spec: etmemv1.EtmemPolicySpec{
			Engine: etmemv1.EngineSpec{Type: "slide", Profile: "conservative"},
		},
	}
	c := fake.NewClientBuilder().WithScheme(s).WithObjects(manualPolicy).Build()
	r := &PodReconciler{Client: c, Scheme: s}

	_, err := r.Reconcile(context.Background(), ctrl.Request{
		NamespacedName: types.NamespacedName{Name: "some-pod", Namespace: "default"},
	})
	require.NoError(t, err)

	var policy etmemv1.EtmemPolicy
	err = c.Get(context.Background(), types.NamespacedName{
		Name: etmemv1.AutoPolicyName, Namespace: "default",
	}, &policy)
	require.NoError(t, err)
	assert.Equal(t, "conservative", policy.Spec.Engine.Profile)
}

func TestPodReconciler_UpdatesProfileOnChange(t *testing.T) {
	s := podScheme()
	pod := &corev1.Pod{
		ObjectMeta: metav1.ObjectMeta{
			Name: "pod1", Namespace: "default",
			Labels:      map[string]string{etmemv1.LabelEnable: "true"},
			Annotations: map[string]string{etmemv1.AnnotationProfile: "extreme"},
		},
		Spec:   corev1.PodSpec{NodeName: "node1"},
		Status: corev1.PodStatus{Phase: corev1.PodRunning},
	}
	autoPolicy := &etmemv1.EtmemPolicy{
		ObjectMeta: metav1.ObjectMeta{
			Name: etmemv1.AutoPolicyName, Namespace: "default",
			Labels: map[string]string{etmemv1.LabelAutoGenerated: "true"},
		},
		Spec: etmemv1.EtmemPolicySpec{
			Selector: &metav1.LabelSelector{
				MatchLabels: map[string]string{etmemv1.LabelEnable: "true"},
			},
			Engine: etmemv1.EngineSpec{Type: "slide", Profile: "moderate"},
		},
	}
	c := fake.NewClientBuilder().WithScheme(s).WithObjects(pod, autoPolicy).WithStatusSubresource(&etmemv1.EtmemPolicy{}).Build()
	r := &PodReconciler{Client: c, Scheme: s}

	_, err := r.Reconcile(context.Background(), ctrl.Request{
		NamespacedName: types.NamespacedName{Name: "pod1", Namespace: "default"},
	})
	require.NoError(t, err)

	var policy etmemv1.EtmemPolicy
	err = c.Get(context.Background(), types.NamespacedName{
		Name: etmemv1.AutoPolicyName, Namespace: "default",
	}, &policy)
	require.NoError(t, err)
	assert.Equal(t, "extreme", policy.Spec.Engine.Profile)
}
