[project]
name=default-multiproc-test-sh
scan_type=page
loop=1
interval=1
sleep=1
sysmem_threshold=95
swapcache_high_wmark=5
swapcache_low_wmark=3

[engine]
name=slide
project=default-multiproc-test-sh

[task]
project=default-multiproc-test-sh
engine=slide
name=default-multiproc-test-sh_task_0
type=name
value=sh
T=1
max_threads=2
swap_flag=no
