apiVersion: etmem.openeuler.io/v1alpha1
kind: EtmemNodeState
metadata:
  creationTimestamp: "2026-04-15T12:22:27Z"
  generation: 1
  name: cp0
  resourceVersion: "12957066"
  uid: ec10ec17-ac23-4a36-9c4b-e4baa608c175
spec: {}
status:
  etmemdReady: false
  metrics:
    totalManagedPods: 2
  nodeName: cp0
  socketReachable: false
  tasks:
  - podName: memhog-test
    podUID: ec6b2ec4-ca48-424b-bac8-91f7ef4b0fde
    policyRef:
      name: etmem-auto
      namespace: default
    processes:
    - name: memhog
      pid: 0
    projectName: default-memhog-test-memhog
    state: running
  - podName: multiproc-test
    podUID: 0a617848-6d85-4f9e-b289-96db0ab92062
    policyRef:
      name: etmem-auto
      namespace: default
    processes:
    - name: sh
      pid: 0
    projectName: default-multiproc-test-sh
    state: running
  - podName: multiproc-test
    podUID: 0a617848-6d85-4f9e-b289-96db0ab92062
    policyRef:
      name: etmem-auto
      namespace: default
    processes:
    - name: memeat1
      pid: 0
    projectName: default-multiproc-test-memeat1
    state: running
  - podName: multiproc-test
    podUID: 0a617848-6d85-4f9e-b289-96db0ab92062
    policyRef:
      name: etmem-auto
      namespace: default
    processes:
    - name: memeat2
      pid: 0
    projectName: default-multiproc-test-memeat2
    state: running
