operator:
  image: etmem-operator:v0.4.0-pid
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

agent:
  image: etmem-agent:v0.4.0-pid
  reconcileInterval: 30s
  socketName: etmemd_socket
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 512Mi

rbac:
  create: true

serviceAccount:
  operator:
    name: etmem-operator
  agent:
    name: etmem-agent
