[project]
name=manual-name-99
scan_type=page
loop=1
interval=1
sleep=1
sysmem_threshold=99
swapcache_high_wmark=5
swapcache_low_wmark=3

[engine]
name=slide
project=manual-name-99

[task]
project=manual-name-99
engine=slide
name=manual-name-99_task_0
type=name
value=memhog
T=1
max_threads=2
swap_flag=no
