[project]
name=manual-memhog
scan_type=page
loop=1
interval=1
sleep=1
sysmem_threshold=30
swapcache_high_wmark=5
swapcache_low_wmark=3

[engine]
name=slide
project=manual-memhog

[task]
project=manual-memhog
engine=slide
name=manual-memhog_task
type=pid
value=3637867
T=1
max_threads=2
swap_flag=no
